"""add_task_expiry

Revision ID: 32c843eb8225
Revises: a53a22092259
Create Date: 2025-05-13 08:09:32.860801

"""

from alembic import op
import sqlalchemy as sa
import enum
import json
from sqlalchemy import Boolean, Column, DateTime, Enum, ForeignKey, Index, Integer, String, Text, text
from resinkit_api.db.models import JSONString, TaskStatus


# revision identifiers, used by Alembic.
revision = "32c843eb8225"
down_revision = "a53a22092259"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("expires_at", sa.DateTime(), nullable=True))
        batch_op.create_index("idx_tasks_expires_at", ["expires_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index("idx_tasks_expires_at")
        batch_op.drop_column("expires_at")

    # ### end Alembic commands ###
