# Use MySQL as the base image
# FROM mysql:latest
FROM mysql:8.0.40

# Switch to root to install packages
USER root

# Install necessary tools
RUN microdnf update && microdnf install -y vim

# Copy MySQL configuration file
COPY ../resources/test-mysql/my.cnf /etc/mysql/conf.d/my.cnf

## Copy initialization SQL file
COPY ../resources/test-mysql/create_tables.sql /docker-entrypoint-initdb.d/

# Set environment variables
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_RESINKIT_PASSWORD=resinkit_mysql_password
ENV MYSQL_TCP_PORT=3306
ENV MYSQLX_TCP_PORT=33060

# Ensure MySQL has proper permissions on the data directory
RUN chown -R mysql:mysql /var/lib/mysql

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

EXPOSE 3306 33060
CMD ["mysqld"]

## Docker commands:
# docker stop resinkit-testmysql
# docker rm resinkit-testmysql
# docker build -t ai.resink.kit.testmysql -f Dockerfile.testmysql .
# docker run -d --name resinkit-testmysql -p 3306:3306 ai.resink.kit.testmysql
# MYSQL_PWD=rootpassword mysql -u root $MYSQL_DATABASE -e 'select 1'

## Log into the container
# docker exec -it $(docker ps | grep testmysql | awk '{print $NF}') /bin/bash
# python /usr/local/bin/generate_data.py
# docker exec -it $(docker ps | grep testmysql | awk '{print $NF}') generate_data.py
