task_type: flink_cdc_pipeline
name: MySQL to Doris Sync Pipeline
description: Synchronization of all MySQL tables to Doris
task_timeout_seconds: 300

pipeline:
  ################################################################################
  # Description: Sync MySQL all tables to Doris
  ################################################################################
  source:
  type: mysql
  hostname: localhost
  port: 3306
  username: root
  password: 123456
  tables: app_db.\.*
  server-id: 5400-5404
  server-time-zone: UTC

  sink:
    type: doris
    fenodes: 127.0.0.1:8030
    username: root
    password: ""
    table.create.properties.light_schema_change: true
    table.create.properties.replication_num: 1

  pipeline:
  name: Sync MySQL Database to Doris
  parallelism: 2

resources:
  flink_cdc_jars:
    - name: MySQL Pipeline Connector 3.3.0
      type: lib
      source: download
      location: https://repo1.maven.org/maven2/org/apache/flink/flink-cdc-pipeline-connector-mysql/3.3.0/flink-cdc-pipeline-connector-mysql-3.3.0.jar

    - name: Apache Doris Pipeline Connector 3.3.0
      type: lib
      source: download
      location: https://repo1.maven.org/maven2/org/apache/flink/flink-cdc-pipeline-connector-doris/3.3.0/flink-cdc-pipeline-connector-doris-3.3.0.jar

    - name: MySQL Connector Java
      type: classpath
      source: download
      location: https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.27/mysql-connector-java-8.0.27.jar
  flink_jars:
    - name: MySQL Connector Java
      download_link: https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.27/mysql-connector-java-8.0.27.jar

# Flink environment settings
environment:
  parallelism: 2
  checkpoint_interval: 60s
  restart_strategy: fixed-delay
  restart_attempts: 3
  restart_delay: 10s
  state_backend: rocksdb

# Runtime configuration
runtime:
  job_name: Sync MySQL Database to Doris
  savepoint_path: null
  allow_non_restored_state: false
